pygments: true
url: http://blog.koboyz.org
lsi: false
future: false
destination: build
source: source
permalink: /:year-:month-:day-:title.html
author: Kevin Disneur
email: kevin@koboyz.org
markdown: redcarpet
redcarpet:
  extensions: [no_intra_emphasis, fenced_code_blocks, autolink, tables, with_toc_data]

main_site_color: '#e74c3c'

social:
  github: kdisneur
  linkedin: disneurkevin
  twitter: kdisneur
google_analytics_key: UA-xxxx-x
