#!/bin/bash
set -e

BUCKET=s3://archives-disneur-me

echo "Build jekyll... "
jekyll build

pushd build &> /dev/null

echo "Sync .html"
s3cmd sync --acl-public --exclude 'assets/' --include  '*.html' --add-header="Cache-Control: max-age=7200, must-revalidate" --config="../s3cfg" . ${BUCKET}

echo "Sync assets files... "
s3cmd sync --acl-public --exclude '*.html' --add-header="Expires: Sat, 20 Nov 2020 18:46:39 GMT" --add-header="Cache-Control: max-age=6048000" --config="../s3cfg" . ${BUCKET}

echo "Remove old files"
s3cmd sync --delete-removed --config="../s3cfg" . ${BUCKET}

popd &> /dev/null
